# Generated by Django 4.0 on 2021-12-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.CharField(max_length=300)),
                ('price', models.CharField(default='', max_length=10)),
                ('pub_date', models.DateField()),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('prod_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
